### ISSUE TITLE
Drag & Drop reorder

### ISSUE THREAD

**Issue by bajki** [mblarsen/shortcode-editor#1]
It would be superb if this option can be done!!

Ivan

**Comment by mblarsen** [comment]
Hi Ivan, that wouldn't be hard to add.

This is only and example for how to use the [shortcode-tokenizer](https://github.com/mblarsen/shortcode-tokenizer). I have no intention of developing on it. Fell free to fork it and build on top it.

I'm working on a tutorial (with code) that has a cleaner implementation than this one, should you be interest.

**Comment by bajki** [comment]
Yes I would be interested..

pet, 15. lip 2018. 17:17 Michael Bøcker-Larsen <notifications@github.com>
je napisao:
